### ISSUE TITLE
Totally Broken HitQueue

### ISSUE THREAD

**Issue by BlowaXD** [OpenNos/OpenNos#1665]
Lastests commits to manage HitQueue totally broke it.

It looks like when you attack, corpse to corpse, a monster that start moving, you are frozen.

You have to relog to unfreeze yourself.

By the way, no errors on console, looking forward because it's really, really annoying.

**Comment by Uportorst** [comment]
True

**Comment by Pescatore981** [comment]
quando riapre il server?

**Comment by Pescatore981** [comment]
when you open the server?

**Comment by MasterDomino** [comment]
english only please, and edit your comment dont create new one, we get spam on our discord bot >.<

**Comment by Pescatore981** [comment]
verso che ora lo attivano ?

**Comment by Pescatore981** [comment]
to now activate it?

**Comment by BlowaXD** [comment]
Seems fixed in last update

**Comment by Uppermost** [comment]
fixed

**Comment by BlowaXD** [comment]
Partially fixed, it happens again sometimes, clearly not as much as before but still happens.
