### ISSUE TITLE
Trade Bug

### ISSUE THREAD

**Issue by Dactylr** [OpenNos/OpenNos#306]
[Trade Bug](http://sendvid.com/vbum9k5r)

Self Trading should be disabled

**Comment by Uppermost** [comment]
Thanks for your report will be fix soon

**Comment by Dactylr** [comment]
The Bug is still not fixed you can duplicate your Items still

**Comment by 0Lucifer0** [comment]
And now?

**Comment by Dactylr** [comment]
The duplicate Bug is still there, you should disable to send `exc_list ` multiple times and outside the trade too

**Comment by 0Lucifer0** [comment]
I dont understand How you could bypass It cause its not possible to validate With same user

**Comment by Dactylr** [comment]
Yeah but you can still use it when you trade with an another Charakter

**Comment by Dactylr** [comment]
[Another method with item drop](http://sendvid.com/wdu7d77x)

**Comment by genyx** [comment]
How is this managed on official?

**Comment by 0Lucifer0** [comment]
Idk but we just need to forbed put or move when tradding

**Comment by 0Lucifer0** [comment]
should be fixed

**Comment by Dactylr** [comment]
[Its still not complete fixed](http://sendvid.com/ibvdghcy)
The other Character receives the item even if you drop the item..

**Comment by genyx** [comment]
@Dactylr Thank you man!

**Comment by Dactylr** [comment]
No Problem @genyx, in the official the trade closes immediately when you mv or drop the item

**Comment by Dactylr** [comment]
You should handle this like the official and close the trade immediately when the user wants to mv, drop or delete the item in trade because its still not fixed

**Comment by 0Lucifer0** [comment]
Hum are you sure cause we dont care about slot so now if you move It It use the right item

**Comment by Dactylr** [comment]
[move_item in trade](http://sendvid.com/vps68b9p) 
___
[drop bug](http://sendvid.com/lq1efrbk) - when you want to drop an item in trade, you cant drop any item after trade
