### ISSUE TITLE
Shop Bugs

### ISSUE THREAD

**Issue by Dactylr** [OpenNos/OpenNos#319]
[Shop Bug #1](http://sendvid.com/97r52h6n)
[Shop Bug #2](http://sendvid.com/hertkxli)
the same when you delete the item, you can still buy it
___
Shop should close automatically if there are no more Items to buy too..

**Comment by Uppermost** [comment]
Will soon be repaired

**Comment by 0Lucifer0** [comment]
should be fixed ;D

**Comment by Dactylr** [comment]
[Another Shop/Item Bug](http://sendvid.com/ovjkicic)
___
[Shop Bug #1 - move item in shop](http://sendvid.com/97r52h6n) -> is still not fixed
